version: '3'
services:
  postgres:
    image: postgres:16.0-alpine
    ports:
      - 5432:5432
    volumes:
      - duretrip-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount init.sql as an initialization script
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Duretrip@2023
      POSTGRES_DB: duretrip
      
  # mysql:
  #   image: mysql:latest
  #   container_name: mysql_container
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_USER: test
  #     MYSQL_PASSWORD: test
  #   networks:
  #     - mynetwork
  #   ports:
  #     - "3308:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount init.sql as an initialization script
    # command: --default-authentication-plugin=mysql_native_password

  rabbitmq:
    image: rabbitmq:3-management
    # image: "rabbitmq:3.13.0-rc.2-management-alpine"
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # RabbitMQ management plugin
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./init-rabbitmq.sh:/usr/local/bin/init-rabbitmq.sh
    entrypoint: /bin/sh
    command: -c "chmod +x /usr/local/bin/init-rabbitmq.sh && /usr/local/bin/init-rabbitmq.sh"


  redis1:
    image: "redis:latest"
    container_name: redis_api_gateway
    ports:
      - "6381:6379"
    environment:
      - REDIS_PASSWORD=password

  redis2:
    image: "redis:latest"
    container_name: redis2_container
    ports:
      - "6380:6379" # Map to a different port
    environment:
      - REDIS_PASSWORD=redis_password_2

volumes:
  # mysql_data:
  duretrip-db:
  
networks:
  mynetwork:
