version: '3.7'

services:
  main:
    container_name: auth
    build:
      context: .
      dockerfile: Dockerfile
    # image: duretrip/api-gateway:131dca173117cd7bd9ad35b8728d4e60fd699a26
    restart: always
    ports:
      - 8006:8006
    env_file:
      - .env.docker
    # volumes:
    #   - ./wait-for-it.sh:/opt/wait-for-it.sh  # Mount init.sql as an initialization script
    #   - ./startup.docker.sh:/docker-entrypoint-initdb.d/startup.docker.sh  # Mount init.sql as an initialization script
    # command: /docker-entrypoint-initdb.d/startup.docker.sh


      