apiVersion: apps/v1
kind: Deployment
metadata:
  name: jet-app
  labels:
    app: jet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jet-app
  template:
    metadata:
      labels:
        app: jet-app
    spec:
      containers:
        - name: jet-app
          image: duretrip/jet:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8008
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.2"
            limits:
              memory: "512Mi"
              cpu: "0.5"
          env:
            - name: DATABASE_TYPE
              value: {{DATABASE_TYPE}}
            - name: DATABASE_NAME
              value: {{JET_DB_NAME}}
            - name: DATABASE_HOST
              value: {{DATABASE_HOST}}

            - name: DATABASE_PORT
              value: {{DATABASE_PORT}}

            - name: JET_DATABASE_URL  # Setting Database name from configMap
              value: "{{DATABASE_TYPE}}://{{JET_DB_USER}}:{{JET_DB_PASSWORD}}@{{DATABASE_HOST}}:{{DATABASE_PORT}}/{{JET_DB_NAME}}"

            - name: DATABASE_USERNAME
              value: {{RABBITMQ_USER_NAME}}

            - name: DATABASE_PASSWORD
              value: {{RABBITMQ_USER_PASSWORD}}

            - name: RABBITMQ_CONNECTION_URL
              value: amqp://{{RABBITMQ_USER_NAME}}:{{RABBITMQ_USER_PASSWORD}}@{{RABBITMQ_HOST}}:{{RABBITMQ_PORT}}

            - name: RABBITMQ_AUTH_QUEUE
              value: {{RABBITMQ_AUTH_QUEUE}}
                  
            - name: RABBITMQ_JET_QUEUE
              value: {{RABBITMQ_JET_QUEUE}}

            - name: RABBITMQ_API_GATEWAY_QUEUE
              value: {{RABBITMQ_API_GATEWAY_QUEUE}}

            - name: APP_PORT
              value: "8008"

---
apiVersion: v1
kind: Service
metadata:
  name: jet-svc
spec:
  selector:
    app: jet-app
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8008
      protocol: TCP
