apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-init-script
data:
  init-rabbitmq.sh: |
    # Contents of your init-rabbitmq.sh script
    #!/bin/bash

    # Function to check if RabbitMQ service is available
    wait_for_rabbitmq() {
        until nslookup rabbitmq-service; do
            echo "Waiting for RabbitMQ service..."
            sleep 2
        done
    }

    # Wait for RabbitMQ service to be available
    wait_for_rabbitmq

    # Wait additional time if needed
    # sleep 30  # Adjust the sleep time if necessary

    # RabbitMQ setup commands
    rabbitmqctl add_user ${RABBITMQ_USER_NAME} ${RABBITMQ_USER_PASSWORD}
    rabbitmqctl set_user_tags ${RABBITMQ_USER_NAME} administrator
    rabbitmqctl set_permissions -p / ${RABBITMQ_USER_NAME} ".*" ".*" ".*"
    rabbitmqadmin declare queue name=${RABBITMQ_AUTH_QUEUE} durable=true
    rabbitmqadmin declare queue name=${RABBITMQ_JET_QUEUE} durable=true
    rabbitmqadmin declare queue name=${RABBITMQ_HOTEL_QUEUE} durable=true
    rabbitmqadmin declare queue name=${RABBITMQ_API_GATEWAY_QUEUE} durable=true

    # Output a message indicating the setup is complete
    echo "RabbitMQ setup is complete."
