apiVersion: v1
kind: ConfigMap
metadata:
  name: init-script
data:
  init-rabbitmq.sh: |
    # Contents of your init-rabbitmq.sh script
    #!/bin/bash

    # Start RabbitMQ
    rabbitmq-server -detached

    # # Wait for RabbitMQ to fully start (you may need to adjust the sleep time)
    sleep 30

    rabbitmqctl add_user {{RABBITMQ_USER_NAME}} {{RABBITMQ_USER_PASSWORD}}
    rabbitmqctl set_user_tags {{RABBITMQ_USER_NAME}} administrator
    rabbitmqctl set_permissions -p / {{RABBITMQ_USER_NAME}} ".*" ".*" ".*"
    rabbitmqadmin declare queue name={{RABBITMQ_AUTH_QUEUE}} durable=true
    rabbitmqadmin declare queue name={{RABBITMQ_JET_QUEUE}} durable=true
    rabbitmqadmin declare queue name={{RABBITMQ_HOTEL_QUEUE}} durable=true
    rabbitmqadmin declare queue name={{RABBITMQ_API_GATEWAY_QUEUE}} durable=true

    # Output a message indicating the setup is complete
    echo "RabbitMQ setup is complete."

    # Keep the script running to keep the container alive
    tail -f /dev/null
