apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: {{RABBITMQ_PORT}}  # RabbitMQ default port
            - containerPort: 15672 # RabbitMQ Management Plugin port
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{RABBITMQ_DEFAULT_USER}}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{RABBITMQ_DEFAULT_PASS}}

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  type: LoadBalancer
  ports:
    - name: rabbitmq-port-5672
      protocol: TCP
      port: {{RABBITMQ_PORT}}  # Expose the RabbitMQ default port
      targetPort: {{RABBITMQ_PORT}}
    - name: rabbitmq-port-15672
      protocol: TCP
      port: 15672 # Expose the RabbitMQ Management Plugin port
      targetPort: 15672
