apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
spec:
  volumes:
    - name: rabbitmq-config
      configMap:
        name: rabbitmq-config
    - name: init-script
      configMap:
        name: init-script
  containers:
    - name: rabbitmq-container
      image: rabbitmq:3-management
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"
      volumeMounts:
        - name: init-script
          mountPath: /usr/local/bin/init-rabbitmq.sh
          subPath: init-rabbitmq.sh
      command: ["/bin/sh", "-c"]
      args:
        - "chmod +x /usr/local/bin/init-rabbitmq.sh && /usr/local/bin/init-rabbitmq.sh"
