---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.0-alpine
          ports:
          - containerPort: {{DATABASE_PORT}}
          env:
            - name: POSTGRES_USER
              value: {{DATABASE_MASTER_BASE_USER}}
            - name: POSTGRES_PASSWORD
              value: {{DATABASE_MASTER_BASE_PASSWORD}}
          volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
          - name: postgres-init-scripts
            mountPath: /docker-entrypoint-initdb.d
            subPath: init.sql
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-claim
        - name: postgres-init-scripts
          configMap:
            name: postgres-init-scripts

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: {{DATABASE_PORT}}
    targetPort: {{DATABASE_PORT}}