apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.0-alpine
          ports:
          - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{DATABASE_MASTER_BASE_USER}}
            - name: POSTGRES_PASSWORD
              value: {{DATABASE_MASTER_BASE_PASSWORD}}
          volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
          - name: init-scripts
            mountPath: /docker-entrypoint-initdb.d

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
