apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  rabbitmq.config: |
    # Contents of your rabbitmq.config file
    [
      {rabbit, [
        {loopback_users, []}  % Disable loopback users (e.g., guest)
      ]}
    ].
  RABBITMQ_DEFAULT_USER: {{RABBITMQ_DEFAULT_USER}}
  RABBITMQ_DEFAULT_PASS: {{RABBITMQ_DEFAULT_PASS}}
  RABBITMQ_URL: amqp://{{RABBITMQ_USER_NAME}}:{{RABBITMQ_USER_PASSWORD}}@{{RABBITMQ_HOST}}:{{RABBITMQ_PORT}}