name: Build and Deploy to GKE

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

env:
  GAR_LOCATION: us-central1 # TODO: update region of the Artifact Registry
  GKE_CLUSTER: ${{ secrets.GKE_PROD_CLUSTER_NAME}}    # TODO: update to cluster name
  GKE_ZONE: ${{ secrets.GKE_PROD_CLUSTER_ZONE}}   # TODO: update to cluster zone
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  test_replace:
    # needs: [setup-and-deploy-to-cluster-dev]

    name: Test Replacement
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    env:
      DATABASE_TYPE: ${{ secrets.DATABASE_TYPE }}
      AUTH_DB_NAME: ${{ secrets.AUTH_DB_NAME }}
      RABBITMQ_JET_QUEUE: ${{ secrets.RABBITMQ_JET_QUEUE }}
      RABBITMQ_API_GATEWAY_QUEUE: ${{ secrets.RABBITMQ_API_GATEWAY_QUEUE }}
      RABBITMQ_USER_NAME: ${{ secrets.RABBITMQ_USER_NAME }}
      RABBITMQ_USER_PASSWORD: ${{ secrets.RABBITMQ_USER_PASSWORD }}
      RABBITMQ_HOST: ${{ secrets.RABBITMQ_HOST }}
      RABBITMQ_PORT: ${{ secrets.RABBITMQ_PORT }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Replace placeholders in YML script
      run: |
          sed -i "s|{{DATABASE_TYPE}}|$DATABASE_TYPE|g" k8s/api-gateway.yml
          sed -i "s|{{AUTH_DB_NAME}}|$AUTH_DB_NAME|g" k8s/api-gateway.yml
          sed -i "s|{{RABBITMQ_JET_QUEUE}}|$RABBITMQ_JET_QUEUE|g" k8s/api-gateway.yml
          sed -i "s|{{RABBITMQ_API_GATEWAY_QUEUE}}|$RABBITMQ_API_GATEWAY_QUEUE|g" k8s/api-gateway.yml
          sed -i "s|{{RABBITMQ_USER_NAME}}|$RABBITMQ_USER_NAME|g" k8s/api-gateway.yml
          sed -i "s|{{RABBITMQ_USER_PASSWORD}}|$RABBITMQ_USER_PASSWORD|g" k8s/api-gateway.yml
          sed -i "s|{{RABBITMQ_HOST}}|$RABBITMQ_HOST|g" k8s/api-gateway.yml
          sed -i "s|{{RABBITMQ_PORT}}|$RABBITMQ_PORT|g" k8s/api-gateway.yml
    - name: Echo contents of api-gateway.yml
      run: cat k8s/api-gateway.yml

    
       